# Generated by Django 3.1.2 on 2020-11-02 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('student_adm', models.CharField(max_length=30)),
                ('student_date_of_admission', models.DateField()),
                ('std_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.course')),
            ],
        ),
    ]
